force-app/main/default/objects/Airport__c/fields/IATA_Code__c.field-meta.xml
<CustomField>
    <fullName>IATA_Code__c</fullName>
    <label>IATA Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AirportController.cls
/**
* @author Antonio Lebrero
* @date 2024
*
* @description Trigger Handler on Airport object
*/
public with sharing class AirportController {
    /*******************************************************************************************************
    * @description Returns a list of available airports with the IATA code given
    * @param searchText the value of the input
    * @return the list of airports with the same IATA code that appears in the input
    */
    @AuraEnabled(cacheable=true)
    public static List<Airport__c> searchAirports(String searchText) {
        List<Airport__c> airports = [SELECT Id, Name, IATA_Code__c FROM Airport__c WHERE IATA_Code__c LIKE :searchText LIMIT 10];
        return airports;
    }
}